/** Default number of photos per page. */
const IMAGES_PER_PAGE = 12;

/**
 * Valid per-page options. Each value is a multiple of 6 (LCM of 1, 2, 3),
 * so results divide evenly across 1-, 2-, and 3-column grid layouts.
 * Max is 30 per the Unsplash API limit.
 */
const PER_PAGE_OPTIONS = [12, 18, 24, 30];

/** Maximum number of pages supported by the Unsplash search API. */
const UNSPLASH_MAX_PAGES = 200;

/** Preset search category labels shown as filter buttons on the home page. */
const imageButtons = [
  "animals",
  "anime",
  "art",
  "food",
  "home",
  "music",
  "nature",
  "seasons",
  "space",
  "sports",
  "travel",
  "wallpaper",
];

/** Supported languages for the Unsplash search beta. */
const LANGUAGES: { code: string; label: string }[] = [
  { code: "af", label: "Afrikaans" },
  { code: "sq", label: "Albanian" },
  { code: "am", label: "Amharic" },
  { code: "ar", label: "Arabic" },
  { code: "hy", label: "Armenian" },
  { code: "as", label: "Assamese" },
  { code: "az", label: "Azerbaijani (Latin)" },
  { code: "bn", label: "Bangla" },
  { code: "ba", label: "Bashkir" },
  { code: "eu", label: "Basque" },
  { code: "bs", label: "Bosnian (Latin)" },
  { code: "bg", label: "Bulgarian" },
  { code: "yue", label: "Cantonese (Traditional)" },
  { code: "ca", label: "Catalan" },
  { code: "lzh", label: "Chinese (Literary)" },
  { code: "zh-Hans", label: "Chinese Simplified" },
  { code: "zh-Hant", label: "Chinese Traditional" },
  { code: "hr", label: "Croatian" },
  { code: "cs", label: "Czech" },
  { code: "da", label: "Danish" },
  { code: "prs", label: "Dari" },
  { code: "dv", label: "Divehi" },
  { code: "nl", label: "Dutch" },
  { code: "en", label: "English" },
  { code: "et", label: "Estonian" },
  { code: "fo", label: "Faroese" },
  { code: "fj", label: "Fijian" },
  { code: "fil", label: "Filipino" },
  { code: "fi", label: "Finnish" },
  { code: "fr", label: "French" },
  { code: "fr-ca", label: "French (Canada)" },
  { code: "gl", label: "Galician" },
  { code: "ka", label: "Georgian" },
  { code: "de", label: "German" },
  { code: "el", label: "Greek" },
  { code: "gu", label: "Gujarati" },
  { code: "ht", label: "Haitian Creole" },
  { code: "he", label: "Hebrew" },
  { code: "hi", label: "Hindi" },
  { code: "mww", label: "Hmong Daw (Latin)" },
  { code: "hu", label: "Hungarian" },
  { code: "is", label: "Icelandic" },
  { code: "id", label: "Indonesian" },
  { code: "ikt", label: "Inuinnaqtun" },
  { code: "iu", label: "Inuktitut" },
  { code: "iu-Latn", label: "Inuktitut (Latin)" },
  { code: "ga", label: "Irish" },
  { code: "it", label: "Italian" },
  { code: "ja", label: "Japanese" },
  { code: "kn", label: "Kannada" },
  { code: "kk", label: "Kazakh" },
  { code: "km", label: "Khmer" },
  { code: "ko", label: "Korean" },
  { code: "ku", label: "Kurdish (Central)" },
  { code: "kmr", label: "Kurdish (Northern)" },
  { code: "ky", label: "Kyrgyz (Cyrillic)" },
  { code: "lo", label: "Lao" },
  { code: "lv", label: "Latvian" },
  { code: "lt", label: "Lithuanian" },
  { code: "mk", label: "Macedonian" },
  { code: "mg", label: "Malagasy" },
  { code: "ms", label: "Malay (Latin)" },
  { code: "ml", label: "Malayalam" },
  { code: "mt", label: "Maltese" },
  { code: "mi", label: "Maori" },
  { code: "mr", label: "Marathi" },
  { code: "mn-Cyrl", label: "Mongolian (Cyrillic)" },
  { code: "mn-Mong", label: "Mongolian (Traditional)" },
  { code: "my", label: "Myanmar" },
  { code: "ne", label: "Nepali" },
  { code: "nb", label: "Norwegian" },
  { code: "or", label: "Odia" },
  { code: "ps", label: "Pashto" },
  { code: "fa", label: "Persian" },
  { code: "pl", label: "Polish" },
  { code: "pt", label: "Portuguese (Brazil)" },
  { code: "pt-pt", label: "Portuguese (Portugal)" },
  { code: "pa", label: "Punjabi" },
  { code: "otq", label: "Queretaro Otomi" },
  { code: "ro", label: "Romanian" },
  { code: "ru", label: "Russian" },
  { code: "sm", label: "Samoan (Latin)" },
  { code: "sr-Cyrl", label: "Serbian (Cyrillic)" },
  { code: "sr-Latn", label: "Serbian (Latin)" },
  { code: "sk", label: "Slovak" },
  { code: "sl", label: "Slovenian" },
  { code: "so", label: "Somali (Arabic)" },
  { code: "es", label: "Spanish" },
  { code: "sw", label: "Swahili (Latin)" },
  { code: "sv", label: "Swedish" },
  { code: "ty", label: "Tahitian" },
  { code: "ta", label: "Tamil" },
  { code: "tt", label: "Tatar (Latin)" },
  { code: "te", label: "Telugu" },
  { code: "th", label: "Thai" },
  { code: "bo", label: "Tibetan" },
  { code: "ti", label: "Tigrinya" },
  { code: "to", label: "Tongan" },
  { code: "tr", label: "Turkish" },
  { code: "tk", label: "Turkmen (Latin)" },
  { code: "uk", label: "Ukrainian" },
  { code: "hsb", label: "Upper Sorbian" },
  { code: "ur", label: "Urdu" },
  { code: "ug", label: "Uyghur (Arabic)" },
  { code: "uz", label: "Uzbek (Latin)" },
  { code: "vi", label: "Vietnamese" },
  { code: "cy", label: "Welsh" },
  { code: "yua", label: "Yucatec Maya" },
  { code: "zu", label: "Zulu" },
];

export { imageButtons, IMAGES_PER_PAGE, LANGUAGES, PER_PAGE_OPTIONS, UNSPLASH_MAX_PAGES };
